### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [sidar-qscs/qscs#2]
# Problem

Please remove https://github.com/sidar-qscs/qscs/tree/main/q_scs/__pycache__, it's auto-generated on install. Also fix the link for issue tracker to be https://github.com/sidar-qscs/qscs/issues rather than https://github.com/sidar-qscs/qscs/issues/1

**Comment by sidar-qscs** [comment]
It is fixed.
________________________________
From: mazano ***@***.***>
Sent: Monday, May 16, 2022 7:19 PM
To: sidar-qscs/qscs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sidar-qscs/qscs] Plugin approval (Issue #2)


Problem

Please remove https://github.com/sidar-qscs/qscs/tree/main/q_scs/__pycache__, it's auto-generated on install. Also fix the link for issue tracker to be https://github.com/sidar-qscs/qscs/issues rather than #1<https://github.com/sidar-qscs/qscs/issues/1>

**Comment by sidar-qscs** [comment]
It is fixed.
